name       : bridge-utils
version    : 1.6
release    : 1
source     :
    - https://www.kernel.org/pub/linux/utils/net/bridge-utils/bridge-utils-1.6.tar.gz : e86e7d9aca850869b5505d6377e79005cb7630022f8c624e6db52d877f5bf4cf
license    : GPL-2.0
component  : system.utils
summary    : Bridge Utilities
description: |
    Utilities for configuring the Linux ethernet bridge
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
